using EImzo.Client.Exceptions;

namespace EImzo.Client.Utils;

/// <summary>
/// Helper utilities for E-IMZO Mobile ID-CARD integration (QR codes and Deeplinks).
/// </summary>
public static class EImzoMobileHelper
{
    public const string DeepLinkScheme = "eimzo://sign?qc=";

    /// <summary>
    /// Generates the payload string for E-IMZO Mobile QR code by concatenating
    /// siteId, documentId, and the hex hash of the challenge or document,
    /// followed by the 8-character CRC32 checksum.
    /// </summary>
    /// <param name="siteId">Registered SiteID (e.g. "0000").</param>
    /// <param name="documentId">DocumentID generated by E-IMZO-SERVER.</param>
    /// <param name="hexHash">Hex-encoded digest of the document or challenge (e.g. O'zDSt 1106 / GOST hash).</param>
    /// <returns>Complete QR code payload string.</returns>
    public static string BuildQrCode(string siteId, string documentId, string hexHash)
    {
        if (string.IsNullOrWhiteSpace(siteId))
        {
            throw new EImzoValidationException(nameof(siteId), "SiteId must not be null or empty.");
        }

        if (string.IsNullOrWhiteSpace(documentId))
        {
            throw new EImzoValidationException(nameof(documentId), "DocumentId must not be null or empty.");
        }

        if (string.IsNullOrWhiteSpace(hexHash))
        {
            throw new EImzoValidationException(nameof(hexHash), "HexHash must not be null or empty.");
        }

        var qrBody = $"{siteId.Trim()}{documentId.Trim()}{hexHash.Trim()}";
        var crc32 = Crc32Helper.ComputeHexFromHexString(qrBody);

        return $"{qrBody}{crc32}";
    }

    /// <summary>
    /// Creates a mobile Deeplink URL from a pre-built QR-code payload string.
    /// Format: eimzo://sign?qc={qrCode}
    /// </summary>
    /// <param name="qrCode">The QR code payload string.</param>
    /// <returns>Deeplink URL string.</returns>
    public static string BuildDeepLink(string qrCode)
    {
        if (string.IsNullOrWhiteSpace(qrCode))
        {
            throw new EImzoValidationException(nameof(qrCode), "QrCode must not be null or empty.");
        }

        return $"{DeepLinkScheme}{qrCode.Trim()}";
    }

    /// <summary>
    /// Builds a mobile Deeplink URL directly from siteId, documentId, and hexHash.
    /// </summary>
    /// <param name="siteId">Registered SiteID (e.g. "0000").</param>
    /// <param name="documentId">DocumentID generated by E-IMZO-SERVER.</param>
    /// <param name="hexHash">Hex-encoded digest of the document or challenge.</param>
    /// <returns>Deeplink URL string (eimzo://sign?qc=...).</returns>
    public static string BuildDeepLink(string siteId, string documentId, string hexHash)
    {
        var qrCode = BuildQrCode(siteId, documentId, hexHash);
        return BuildDeepLink(qrCode);
    }

    /// <summary>
    /// Verifies the CRC32 checksum in an E-IMZO QR code payload.
    /// </summary>
    /// <param name="qrCode">The QR code payload string containing the trailing 8-character CRC32.</param>
    /// <returns>True if the checksum matches; otherwise false.</returns>
    public static bool VerifyQrCode(string qrCode)
    {
        if (string.IsNullOrWhiteSpace(qrCode) || qrCode.Length <= 8)
        {
            return false;
        }

        var body = qrCode.Substring(0, qrCode.Length - 8);
        var expectedCrc = qrCode.Substring(qrCode.Length - 8);
        var calculatedCrc = Crc32Helper.ComputeHexFromHexString(body);

        return string.Equals(expectedCrc, calculatedCrc, StringComparison.OrdinalIgnoreCase);
    }
}
