import { EImzoValidationError } from '../errors/e-imzo-validation-error.js';
import { computeHexFromHexString } from './crc32.js';

export const DEEP_LINK_SCHEME = 'eimzo://sign?qc=';

/**
 * Builds the payload string for E-IMZO Mobile QR code by concatenating
 * siteId, documentId, and hex hash of the challenge or document,
 * followed by an 8-character CRC32 checksum.
 *
 * @param siteId Registered SiteID (e.g. "0000").
 * @param documentId DocumentID generated by E-IMZO-SERVER.
 * @param hexHash Hex-encoded digest of the document or challenge.
 * @returns Complete QR code payload string.
 */
export function buildQrCode(siteId: string, documentId: string, hexHash: string): string {
  if (!siteId || siteId.trim().length === 0) {
    throw new EImzoValidationError('siteId', 'siteId must not be null or empty.');
  }

  if (!documentId || documentId.trim().length === 0) {
    throw new EImzoValidationError('documentId', 'documentId must not be null or empty.');
  }

  if (!hexHash || hexHash.trim().length === 0) {
    throw new EImzoValidationError('hexHash', 'hexHash must not be null or empty.');
  }

  const qrBody = `${siteId.trim()}${documentId.trim()}${hexHash.trim()}`;
  const crc32 = computeHexFromHexString(qrBody);

  return `${qrBody}${crc32}`;
}

/**
 * Creates a mobile Deeplink URL from a pre-built QR-code payload string.
 * Format: eimzo://sign?qc={qrCode}
 *
 * @param qrCode The QR code payload string.
 * @returns Deeplink URL string.
 */
export function buildDeepLinkFromQr(qrCode: string): string {
  if (!qrCode || qrCode.trim().length === 0) {
    throw new EImzoValidationError('qrCode', 'qrCode must not be null or empty.');
  }

  return `${DEEP_LINK_SCHEME}${qrCode.trim()}`;
}

/**
 * Builds a mobile Deeplink URL directly from siteId, documentId, and hexHash,
 * or from a pre-built QR code string.
 */
export function buildDeepLink(siteIdOrQrCode: string, documentId?: string, hexHash?: string): string {
  if (documentId !== undefined && hexHash !== undefined) {
    const qrCode = buildQrCode(siteIdOrQrCode, documentId, hexHash);
    return buildDeepLinkFromQr(qrCode);
  }

  return buildDeepLinkFromQr(siteIdOrQrCode);
}

/**
 * Verifies the CRC32 checksum in an E-IMZO QR code payload.
 *
 * @param qrCode The QR code payload string containing the trailing 8-character CRC32.
 * @returns True if checksum is valid; otherwise false.
 */
export function verifyQrCode(qrCode: string): boolean {
  if (!qrCode || qrCode.trim().length <= 8) {
    return false;
  }

  const trimmed = qrCode.trim();
  const body = trimmed.substring(0, trimmed.length - 8);
  const expectedCrc = trimmed.substring(trimmed.length - 8);

  try {
    const calculatedCrc = computeHexFromHexString(body);
    return calculatedCrc.toLowerCase() === expectedCrc.toLowerCase();
  } catch {
    return false;
  }
}
