namespace EImzo.Client.Models.Mobile;

/// <summary>
/// Request parameters for the /frontend/mobile/upload endpoint.
/// </summary>
public class MobileUploadRequest
{
    /// <summary>
    /// Temporary document ID generated by E-IMZO-SERVER.
    /// </summary>
    public string DocumentId { get; set; } = string.Empty;

    /// <summary>
    /// Base64 encoded PKCS#7 Detached document created by the mobile app.
    /// </summary>
    public string Pkcs7Base64 { get; set; } = string.Empty;

    /// <summary>
    /// Serial number of the user's certificate.
    /// </summary>
    public string SerialNumber { get; set; } = string.Empty;

    public MobileUploadRequest()
    {
    }

    public MobileUploadRequest(string documentId, string pkcs7Base64, string serialNumber)
    {
        DocumentId = documentId;
        Pkcs7Base64 = pkcs7Base64;
        SerialNumber = serialNumber;
    }
}
