using System.Text;

namespace EImzo.Client.Models.Mobile;

/// <summary>
/// Request parameters for the /backend/mobile/verify endpoint.
/// </summary>
public class MobileVerifyRequest
{
    /// <summary>
    /// Temporary document ID generated by E-IMZO-SERVER.
    /// </summary>
    public string DocumentId { get; set; } = string.Empty;

    /// <summary>
    /// Base64 encoded document that was signed.
    /// </summary>
    public string DocumentBase64 { get; set; } = string.Empty;

    public MobileVerifyRequest()
    {
    }

    public MobileVerifyRequest(string documentId, string documentBase64)
    {
        DocumentId = documentId;
        DocumentBase64 = documentBase64;
    }

    public MobileVerifyRequest(string documentId, byte[] documentBytes)
    {
        DocumentId = documentId;
        DocumentBase64 = Convert.ToBase64String(documentBytes);
    }

    public MobileVerifyRequest(string documentId, string documentText, Encoding encoding)
    {
        DocumentId = documentId;
        DocumentBase64 = Convert.ToBase64String(encoding.GetBytes(documentText));
    }
}
